#!/usr/bin/env bash
# scaffold-service.sh
# Creates a new JANUS service repository from the janus-engineering template
# Usage: ./scripts/scaffold-service.sh --name NAME --repo REPO --domain DOMAIN --csa CSA [--suite-version VERSION]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TEMPLATE_DIR="${REPO_ROOT}/templates/repository"

# Defaults
SUITE_VERSION=$(cat "${REPO_ROOT}/VERSION")
TARGET_DIR=""

usage() {
  echo "Usage: $0 --name NAME --repo REPO --domain DOMAIN --csa CSA [--suite-version VERSION] [--target-dir DIR]"
  echo ""
  echo "  --name           Service codename (e.g., VENUS)"
  echo "  --repo           Repository name (e.g., venus-v1)"
  echo "  --domain         One-line domain description"
  echo "  --csa            Chief Software Architect name"
  echo "  --suite-version  janus-engineering suite version to target (default: current)"
  echo "  --target-dir     Directory to create the service in (default: ../\$REPO)"
  exit 1
}

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --name) SERVICE_NAME="$2"; shift 2 ;;
    --repo) SERVICE_REPO="$2"; shift 2 ;;
    --domain) SERVICE_DOMAIN="$2"; shift 2 ;;
    --csa) CSA_NAME="$2"; shift 2 ;;
    --suite-version) SUITE_VERSION="$2"; shift 2 ;;
    --target-dir) TARGET_DIR="$2"; shift 2 ;;
    *) echo "Unknown argument: $1"; usage ;;
  esac
done

# Validate required arguments
if [[ -z "${SERVICE_NAME:-}" || -z "${SERVICE_REPO:-}" || -z "${SERVICE_DOMAIN:-}" || -z "${CSA_NAME:-}" ]]; then
  echo "Error: --name, --repo, --domain, and --csa are all required."
  usage
fi

SERVICE_IDENTIFIER=$(echo "${SERVICE_NAME}" | tr '[:upper:]' '[:lower:]')
SERVICE_PREFIX="${SERVICE_NAME}"
DATE=$(date +%Y-%m-%d)

if [[ -z "${TARGET_DIR}" ]]; then
  TARGET_DIR="$(cd "${REPO_ROOT}/.." && pwd)/${SERVICE_REPO}"
fi

# Confirm before proceeding
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "JANUS Service Scaffold"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Service name:    ${SERVICE_NAME}"
echo "Repository:      ${SERVICE_REPO}"
echo "Domain:          ${SERVICE_DOMAIN}"
echo "CSA:             ${CSA_NAME}"
echo "Suite version:   janus-engineering@${SUITE_VERSION}"
echo "Target path:     ${TARGET_DIR}"
echo ""
echo "This will create a new repository directory at the target path."
read -r -p "Proceed? (yes/no): " CONFIRM

if [[ "${CONFIRM}" != "yes" ]]; then
  echo "Aborted."
  exit 0
fi

echo ""
echo "Creating repository..."

# Create directory
if [[ -d "${TARGET_DIR}" ]]; then
  echo "Error: Target directory already exists: ${TARGET_DIR}"
  exit 1
fi

mkdir -p "${TARGET_DIR}"

# Copy template
cp -r "${TEMPLATE_DIR}/." "${TARGET_DIR}/"

# Function to substitute placeholders in a file
substitute_placeholders() {
  local file="$1"
  sed -i.bak \
    -e "s|{{SERVICE_NAME}}|${SERVICE_NAME}|g" \
    -e "s|{{SERVICE_REPO}}|${SERVICE_REPO}|g" \
    -e "s|{{SERVICE_DOMAIN}}|${SERVICE_DOMAIN}|g" \
    -e "s|{{SERVICE_IDENTIFIER}}|${SERVICE_IDENTIFIER}|g" \
    -e "s|{{SERVICE_PREFIX}}|${SERVICE_PREFIX}|g" \
    -e "s|{{CSA_NAME}}|${CSA_NAME}|g" \
    -e "s|{{DATE}}|${DATE}|g" \
    -e "s|{{JANUS_SUITE_VERSION}}|${SUITE_VERSION}|g" \
    "${file}"
  rm -f "${file}.bak"
}

# Substitute placeholders in all text files
find "${TARGET_DIR}" -type f \( -name "*.md" -o -name "*.yaml" -o -name "*.yml" -o -name "*.json" -o -name "*.ts" -o -name "*.js" -o -name "*.sh" \) | while read -r file; do
  substitute_placeholders "${file}"
done

# Create .janus-compliance.yaml
cat > "${TARGET_DIR}/.janus-compliance.yaml" << EOF
# JANUS Compliance Declaration
# Generated by scaffold-service.sh on ${DATE}
# Update janus_engineering_suite_version when upgrading to a new suite release

janus_engineering_suite_version: "${SUITE_VERSION}"
service_name: "${SERVICE_NAME}"
service_repo: "${SERVICE_REPO}"
created_date: "${DATE}"
csa: "${CSA_NAME}"
compliance_exceptions: []
mandatory_only_check: false
EOF

# Initialize git repository
cd "${TARGET_DIR}"
git init
git config user.name "${CSA_NAME}"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Repository created: ${TARGET_DIR}"
echo ""
echo "Next steps:"
echo "  1. cd ${TARGET_DIR}"
echo "  2. Review and fill in all [[FILL:]] markers in docs/"
echo "  3. Create a GitHub repository and push the initial commit"
echo "  4. Configure branch protection rules per the branching strategy"
echo "  5. Add the service to services/registry.yaml in janus-engineering"
echo "  6. Run validate-compliance.sh to confirm compliance"
echo ""
echo "Initial commit command:"
echo "  git add . && git commit -m 'chore: bootstrap ${SERVICE_REPO} from janus-engineering@${SUITE_VERSION}'"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
